name: Make Release Builds

on: [workflow_dispatch]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y libsdl2-dev libsdl2-mixer-dev cmake

      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make -j$(nproc)

      - uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: bin/SpaceCadetPinball

  #build-macos:
  #  runs-on: macos-12
  #  timeout-minutes: 15
  #  steps:
  #    - uses: actions/checkout@v4
  #      with:
  #        ref: master
#
  #    - uses: maxim-lobanov/setup-xcode@v1
  #      with:
  #        xcode-version: 13
#
  #    - run: bash build-mac-app.sh
#
  #    - uses: actions/upload-artifact@v4
  #      with:
  #        name: mac-build
  #        path: SpaceCadetPinball-*-mac.dmg

  build-windows:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      LANG: zh_CN.UTF-8
      LANGUAGE: zh_CN:zh
      LC_ALL: zh_CN.UTF-8
    steps:
      - uses: actions/checkout@v4

      - name: install dependencies
        run: sudo apt-get update && sudo apt-get install -y mingw-w64 cmake gcc-mingw-w64 language-pack-zh-hans

      - name: install sdl2 dll
        run: |
          wget https://github.com/libsdl-org/SDL/releases/download/release-2.32.2/SDL2-devel-2.32.2-mingw.tar.gz -O sdl2.tar.gz
          wget https://github.com/libsdl-org/SDL_mixer/releases/download/release-2.8.1/SDL2_mixer-devel-2.8.1-mingw.tar.gz -O sdl2_mixer.tar.gz
          sudo mkdir -p /usr/local/i686-w64-mingw32
          sudo mkdir -p /usr/local/x86_64-w64-mingw32
          tar -xvf sdl2.tar.gz
          cd SDL2-*
          sudo make install
          sudo make cross
          cd ../
          tar -xvf sdl2_mixer.tar.gz
          cd SDL2_mixer-*
          sudo make install
          sudo make cross

      - name: build
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../mingwcc.cmake
          make -j$(nproc)